// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Skinet.Infrastructure.Data;

#nullable disable

namespace Skinet.Infrastructure.Data.Migrations
{
    [DbContext(typeof(StoreDbContext))]
    partial class StoreDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Skinet.Core.Domain.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("PictureUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<Guid>("ProductBrandID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("ProductTypeID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ProductBrandID");

                    b.HasIndex("ProductTypeID");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("62aafb98-79cb-49c2-9d33-db9227ab2ec4"),
                            Description = "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Maecenas porttitor congue massa. Fusce posuere, magna sed pulvinar ultricies, purus lectus malesuada libero, sit amet commodo magna eros quis urna.",
                            PictureUrl = "images/products/sb-ang1.png",
                            Price = 200m,
                            ProductBrandID = new Guid("04dc1a38-bc24-4dbf-9c44-0f22b01ac3ac"),
                            ProductName = "Angular Speedster Board 2000",
                            ProductTypeID = new Guid("0b266b88-dce6-4f2e-bf86-f9a6e0a5949f")
                        },
                        new
                        {
                            Id = new Guid("95383841-5340-48f3-81d6-7847039792e1"),
                            Description = "Nunc viverra imperdiet enim. Fusce est. Vivamus a tellus.",
                            PictureUrl = "images/products/sb-ang2.png",
                            Price = 150m,
                            ProductBrandID = new Guid("04dc1a38-bc24-4dbf-9c44-0f22b01ac3ac"),
                            ProductName = "Green Angular Board 3000",
                            ProductTypeID = new Guid("0b266b88-dce6-4f2e-bf86-f9a6e0a5949f")
                        },
                        new
                        {
                            Id = new Guid("01d034a3-bf1b-49a5-b114-8faed06054e2"),
                            Description = "Suspendisse dui purus, scelerisque at, vulputate vitae, pretium mattis, nunc. Mauris eget neque at sem venenatis eleifend. Ut nonummy.",
                            PictureUrl = "images/products/sb-core1.png",
                            Price = 180m,
                            ProductBrandID = new Guid("4b86e05b-2152-440b-b946-22e429e9758d"),
                            ProductName = "Core Board Speed Rush 3",
                            ProductTypeID = new Guid("0b266b88-dce6-4f2e-bf86-f9a6e0a5949f")
                        },
                        new
                        {
                            Id = new Guid("71961f22-4acc-4dc9-8309-5bcf074ed707"),
                            Description = "Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Proin pharetra nonummy pede. Mauris et orci.",
                            PictureUrl = "images/products/sb-core2.png",
                            Price = 300m,
                            ProductBrandID = new Guid("4b86e05b-2152-440b-b946-22e429e9758d"),
                            ProductName = "Net Core Super Board",
                            ProductTypeID = new Guid("0b266b88-dce6-4f2e-bf86-f9a6e0a5949f")
                        },
                        new
                        {
                            Id = new Guid("aec70461-2f65-43e8-adc3-b86d84eec0ec"),
                            Description = "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Maecenas porttitor congue massa. Fusce posuere, magna sed pulvinar ultricies, purus lectus malesuada libero, sit amet commodo magna eros quis urna.",
                            PictureUrl = "images/products/sb-react1.png",
                            Price = 250m,
                            ProductBrandID = new Guid("21c5894e-72f8-4ab7-ab08-cf7f2ee4b863"),
                            ProductName = "React Board Super Whizzy Fast",
                            ProductTypeID = new Guid("0b266b88-dce6-4f2e-bf86-f9a6e0a5949f")
                        },
                        new
                        {
                            Id = new Guid("337748c4-071c-475d-8c06-4da68ae08283"),
                            Description = "Aenean nec lorem. In porttitor. Donec laoreet nonummy augue.",
                            PictureUrl = "images/products/sb-ts1.png",
                            Price = 120m,
                            ProductBrandID = new Guid("e595c11b-fc76-4985-90ab-5e455550dece"),
                            ProductName = "Typescript Entry Board",
                            ProductTypeID = new Guid("0b266b88-dce6-4f2e-bf86-f9a6e0a5949f")
                        },
                        new
                        {
                            Id = new Guid("2ba96895-9187-415b-978d-ce14981c1442"),
                            Description = "Fusce posuere, magna sed pulvinar ultricies, purus lectus malesuada libero, sit amet commodo magna eros quis urna.",
                            PictureUrl = "images/products/hat-core1.png",
                            Price = 10m,
                            ProductBrandID = new Guid("4b86e05b-2152-440b-b946-22e429e9758d"),
                            ProductName = "Core Blue Hat",
                            ProductTypeID = new Guid("a0a9db25-63fd-4ac9-ad98-0b8853042aa7")
                        },
                        new
                        {
                            Id = new Guid("86cda00d-9d97-46ea-bbc7-43dc29e0d76c"),
                            Description = "Suspendisse dui purus, scelerisque at, vulputate vitae, pretium mattis, nunc. Mauris eget neque at sem venenatis eleifend. Ut nonummy.",
                            PictureUrl = "images/products/hat-react1.png",
                            Price = 8m,
                            ProductBrandID = new Guid("21c5894e-72f8-4ab7-ab08-cf7f2ee4b863"),
                            ProductName = "Green React Woolen Hat",
                            ProductTypeID = new Guid("a0a9db25-63fd-4ac9-ad98-0b8853042aa7")
                        },
                        new
                        {
                            Id = new Guid("1e05e91e-12e4-4718-8c38-fcadc046b221"),
                            Description = "Fusce posuere, magna sed pulvinar ultricies, purus lectus malesuada libero, sit amet commodo magna eros quis urna.",
                            PictureUrl = "images/products/hat-react2.png",
                            Price = 15m,
                            ProductBrandID = new Guid("21c5894e-72f8-4ab7-ab08-cf7f2ee4b863"),
                            ProductName = "Purple React Woolen Hat",
                            ProductTypeID = new Guid("a0a9db25-63fd-4ac9-ad98-0b8853042aa7")
                        },
                        new
                        {
                            Id = new Guid("b351da0a-1399-4c1a-8f2f-4a0487116b7e"),
                            Description = "Nunc viverra imperdiet enim. Fusce est. Vivamus a tellus.",
                            PictureUrl = "images/products/glove-code1.png",
                            Price = 18m,
                            ProductBrandID = new Guid("fc267da2-0c5d-4609-911a-96ada3b5451f"),
                            ProductName = "Blue Code Gloves",
                            ProductTypeID = new Guid("d4481d8b-9238-4653-bb77-1b6cd13a2b9d")
                        },
                        new
                        {
                            Id = new Guid("c09f0052-3ff9-402e-83e8-83c4f8b59edf"),
                            Description = "Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Proin pharetra nonummy pede. Mauris et orci.",
                            PictureUrl = "images/products/glove-code2.png",
                            Price = 15m,
                            ProductBrandID = new Guid("fc267da2-0c5d-4609-911a-96ada3b5451f"),
                            ProductName = "Green Code Gloves",
                            ProductTypeID = new Guid("d4481d8b-9238-4653-bb77-1b6cd13a2b9d")
                        },
                        new
                        {
                            Id = new Guid("4df4b3fe-7ca4-4043-9a0e-706b564d1bc4"),
                            Description = "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Maecenas porttitor congue massa.",
                            PictureUrl = "images/products/glove-react1.png",
                            Price = 16m,
                            ProductBrandID = new Guid("21c5894e-72f8-4ab7-ab08-cf7f2ee4b863"),
                            ProductName = "Purple React Gloves",
                            ProductTypeID = new Guid("d4481d8b-9238-4653-bb77-1b6cd13a2b9d")
                        },
                        new
                        {
                            Id = new Guid("c542c49a-c793-40ff-bbc5-3223334d5b11"),
                            Description = "Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Proin pharetra nonummy pede. Mauris et orci.",
                            PictureUrl = "images/products/glove-react2.png",
                            Price = 14m,
                            ProductBrandID = new Guid("21c5894e-72f8-4ab7-ab08-cf7f2ee4b863"),
                            ProductName = "Green React Gloves",
                            ProductTypeID = new Guid("d4481d8b-9238-4653-bb77-1b6cd13a2b9d")
                        },
                        new
                        {
                            Id = new Guid("6dc970ce-439a-4da8-8901-d76b06688e7c"),
                            Description = "Suspendisse dui purus, scelerisque at, vulputate vitae, pretium mattis, nunc. Mauris eget neque at sem venenatis eleifend. Ut nonummy.",
                            PictureUrl = "images/products/boot-redis1.png",
                            Price = 250m,
                            ProductBrandID = new Guid("0b03373d-cbf8-4f23-9f0c-b84c2d4a4b1a"),
                            ProductName = "Redis Red Boots",
                            ProductTypeID = new Guid("0a6cfad6-ea3b-481f-a773-458bee602086")
                        },
                        new
                        {
                            Id = new Guid("6c179ac9-fc79-4353-ae64-a814febee317"),
                            Description = "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Maecenas porttitor congue massa. Fusce posuere, magna sed pulvinar ultricies, purus lectus malesuada libero, sit amet commodo magna eros quis urna.",
                            PictureUrl = "images/products/boot-core2.png",
                            Price = 189.99m,
                            ProductBrandID = new Guid("4b86e05b-2152-440b-b946-22e429e9758d"),
                            ProductName = "Core Red Boots",
                            ProductTypeID = new Guid("0a6cfad6-ea3b-481f-a773-458bee602086")
                        },
                        new
                        {
                            Id = new Guid("c5b2627f-1bce-4f5f-98ad-a4cdc47fbb65"),
                            Description = "Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Proin pharetra nonummy pede. Mauris et orci.",
                            PictureUrl = "images/products/boot-core1.png",
                            Price = 199.99m,
                            ProductBrandID = new Guid("4b86e05b-2152-440b-b946-22e429e9758d"),
                            ProductName = "Core Purple Boots",
                            ProductTypeID = new Guid("0a6cfad6-ea3b-481f-a773-458bee602086")
                        },
                        new
                        {
                            Id = new Guid("dbc12ed7-11c1-42ca-970c-db9d62234319"),
                            Description = "Aenean nec lorem. In porttitor. Donec laoreet nonummy augue.",
                            PictureUrl = "images/products/boot-ang2.png",
                            Price = 150m,
                            ProductBrandID = new Guid("04dc1a38-bc24-4dbf-9c44-0f22b01ac3ac"),
                            ProductName = "Angular Purple Boots",
                            ProductTypeID = new Guid("0a6cfad6-ea3b-481f-a773-458bee602086")
                        },
                        new
                        {
                            Id = new Guid("a84e1159-365b-49f1-99e4-818f16879166"),
                            Description = "Suspendisse dui purus, scelerisque at, vulputate vitae, pretium mattis, nunc. Mauris eget neque at sem venenatis eleifend. Ut nonummy.",
                            PictureUrl = "images/products/boot-ang1.png",
                            Price = 180m,
                            ProductBrandID = new Guid("04dc1a38-bc24-4dbf-9c44-0f22b01ac3ac"),
                            ProductName = "Angular Blue Boots",
                            ProductTypeID = new Guid("0a6cfad6-ea3b-481f-a773-458bee602086")
                        });
                });

            modelBuilder.Entity("Skinet.Core.Domain.Entities.ProductBrand", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ProductBrands");

                    b.HasData(
                        new
                        {
                            Id = new Guid("04dc1a38-bc24-4dbf-9c44-0f22b01ac3ac"),
                            Name = "Angular"
                        },
                        new
                        {
                            Id = new Guid("4b86e05b-2152-440b-b946-22e429e9758d"),
                            Name = "NetCore"
                        },
                        new
                        {
                            Id = new Guid("fc267da2-0c5d-4609-911a-96ada3b5451f"),
                            Name = "VS Code"
                        },
                        new
                        {
                            Id = new Guid("21c5894e-72f8-4ab7-ab08-cf7f2ee4b863"),
                            Name = "React"
                        },
                        new
                        {
                            Id = new Guid("e595c11b-fc76-4985-90ab-5e455550dece"),
                            Name = "Typescript"
                        },
                        new
                        {
                            Id = new Guid("0b03373d-cbf8-4f23-9f0c-b84c2d4a4b1a"),
                            Name = "Redis"
                        });
                });

            modelBuilder.Entity("Skinet.Core.Domain.Entities.ProductType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ProductTypes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("0b266b88-dce6-4f2e-bf86-f9a6e0a5949f"),
                            Name = "Boards"
                        },
                        new
                        {
                            Id = new Guid("a0a9db25-63fd-4ac9-ad98-0b8853042aa7"),
                            Name = "Hats"
                        },
                        new
                        {
                            Id = new Guid("0a6cfad6-ea3b-481f-a773-458bee602086"),
                            Name = "Boots"
                        },
                        new
                        {
                            Id = new Guid("d4481d8b-9238-4653-bb77-1b6cd13a2b9d"),
                            Name = "Gloves"
                        });
                });

            modelBuilder.Entity("Skinet.Core.Domain.Entities.Product", b =>
                {
                    b.HasOne("Skinet.Core.Domain.Entities.ProductBrand", "ProductBrand")
                        .WithMany()
                        .HasForeignKey("ProductBrandID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Skinet.Core.Domain.Entities.ProductType", "ProductType")
                        .WithMany()
                        .HasForeignKey("ProductTypeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductBrand");

                    b.Navigation("ProductType");
                });
#pragma warning restore 612, 618
        }
    }
}
